export default {
  dates: { maximum: "2021-11-03", minimum: "2021-09-16" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/Aebz7s8EHQXxHR98J8Vw6QVGggq.jpg",
      genre_ids: [12, 18, 14, 878],
      id: 438631,
      original_language: "en",
      original_title: "Dune",
      overview:
        "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
      popularity: 6245.254,
      poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      release_date: "2021-10-22",
      title: "Dune",
      video: false,
      vote_average: 8,
      vote_count: 2800,
    },
    {
      adult: false,
      backdrop_path: "/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
      genre_ids: [35, 28, 12, 878],
      id: 550988,
      original_language: "en",
      original_title: "Free Guy",
      overview:
        "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
      popularity: 2223.631,
      poster_path: "/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
      release_date: "2021-09-17",
      title: "Free Guy",
      video: false,
      vote_average: 7.8,
      vote_count: 3181,
    },
    {
      adult: false,
      backdrop_path: "/7WJjFviFBffEJvkAms4uWwbcVUk.jpg",
      genre_ids: [12, 14, 35, 28],
      id: 451048,
      original_language: "en",
      original_title: "Jungle Cruise",
      overview:
        "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
      popularity: 735.111,
      poster_path: "/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
      release_date: "2021-09-24",
      title: "Jungle Cruise",
      video: false,
      vote_average: 7.8,
      vote_count: 3042,
    },
    {
      adult: false,
      backdrop_path: "/pUc51UUQb1lMLVVkDCaZVsCo37U.jpg",
      genre_ids: [53, 27],
      id: 482373,
      original_language: "en",
      original_title: "Don't Breathe 2",
      overview:
        "The Blind Man has been hiding out for several years in an isolated cabin and has taken in and raised a young girl orphaned from a devastating house fire. Their quiet life together is shattered when a group of criminals kidnap the girl, forcing the Blind Man to leave his safe haven to save her.",
      popularity: 405.061,
      poster_path: "/r7HEBkkRN93d3eFBZgPJfRaob5p.jpg",
      release_date: "2021-09-17",
      title: "Don't Breathe 2",
      video: false,
      vote_average: 7.7,
      vote_count: 1062,
    },
    {
      adult: false,
      backdrop_path: "/u5Fp9GBy9W8fqkuGfLBuuoJf57Z.jpg",
      genre_ids: [12, 28, 53],
      id: 370172,
      original_language: "en",
      original_title: "No Time to Die",
      overview:
        "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
      popularity: 422.427,
      poster_path: "/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
      release_date: "2021-09-30",
      title: "No Time to Die",
      video: false,
      vote_average: 7.4,
      vote_count: 998,
    },
    {
      adult: false,
      backdrop_path: "/sqmGvNabWUD2hlhEqejksr6HVeX.jpg",
      genre_ids: [18, 36, 10752, 53],
      id: 617653,
      original_language: "en",
      original_title: "The Last Duel",
      overview:
        "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire by challenging him to a duel.",
      popularity: 144.201,
      poster_path: "/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg",
      release_date: "2021-10-22",
      title: "The Last Duel",
      video: false,
      vote_average: 7.6,
      vote_count: 292,
    },
    {
      adult: false,
      backdrop_path: "/dSMmg6BcJoWECA4zzenGejJR0rr.jpg",
      genre_ids: [10749, 35],
      id: 879337,
      original_language: "pa",
      original_title: "Honsla Rakh",
      overview:
        "What happens when a lovable, rooted, desi, Punjabi young man, who's a single father with a seven year old boy attempts to find love again, find a mom for his son, crosses paths with his ex who comes back into the city after a seven year gap? Honsla Rakh, starring Diljit Dosanjh, Sonam Bajwa, Shehnaaz Gill and Shinda Grewal is a romantic comedy set in Vancouver, Canada that has warmth at its center and deals with the emotional bonds between father and child, and love between men and women in modern times.",
      popularity: 30.853,
      poster_path: "/o7OhVQrvu6H6J3o6rrFP1cYBEnS.jpg",
      release_date: "2021-10-15",
      title: "Honsla Rakh",
      video: false,
      vote_average: 2,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/uLZ4Uo8YsO67whKMzlHmyI6ECM8.jpg",
      genre_ids: [27, 18],
      id: 587204,
      original_language: "ta",
      original_title: "IPC 376",
      overview:
        "A Lady cop is dealing with the mysterious disappearances of girls and burning issue , rapes.",
      popularity: 22.933,
      poster_path: "/kI5KaUMpJAP05lwQBg4qHvqcFE2.jpg",
      release_date: "2021-10-28",
      title: "IPC 376",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [53, 18, 9648],
      id: 814030,
      original_language: "ml",
      original_title: "Star",
      overview: "",
      popularity: 26.23,
      poster_path: "/XxpilYkGTjnNOrmOx4syxDtL7f.jpg",
      release_date: "2021-10-29",
      title: "Star",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/2eUIYPfEydDQ7emNm6zHR5YBDS0.jpg",
      genre_ids: [53, 80],
      id: 883735,
      original_language: "ta",
      original_title: "Filter Gold",
      overview: "Deals with the story of three transgenders,",
      popularity: 21.941,
      poster_path: "/n4LQspbG9wdIKO60r6Q6Cjr7HTj.jpg",
      release_date: "2021-10-29",
      title: "Filter Gold",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 813109,
      original_language: "en",
      original_title: "Dammy",
      overview: "A Short Film Directed by Rukshana Tabassum",
      popularity: 21.127,
      poster_path: "/lRZSer6gyKBAbbWIiXvug293W4N.jpg",
      release_date: "2021-10-29",
      title: "Dammy",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/eYGDYMzhUoKTnTgvbW2XIqo6BLJ.jpg",
      genre_ids: [80, 18],
      id: 877587,
      original_language: "ta",
      original_title: "கடைசீல பிரியாணி",
      overview:
        "Chicku Pandi has one day to slip away from his revenge hungry brothers.",
      popularity: 15.87,
      poster_path: "/o6H0LyEfoRyQoiVK28eXcMxyQJZ.jpg",
      release_date: "2021-10-30",
      title: "Kadaseela Biriyani",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/aZ38BOxbbHsqqGxOWo4h7RbGklJ.jpg",
      genre_ids: [27, 35],
      id: 880780,
      original_language: "ta",
      original_title: "இடியட்",
      overview: "",
      popularity: 15.376,
      poster_path: "/2RzgOYP6jMyAKXsi64RKP85ZcXM.jpg",
      release_date: "2021-10-30",
      title: "Idiot",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/ouAEPE6GUBlAbZB9SdmG8vyf58H.jpg",
      genre_ids: [10749],
      id: 716255,
      original_language: "te",
      original_title: "Most Eligible బ్యాచ్‌లర్",
      overview:
        "A well-educated, ‘settled’ NRI falls for a stand-up comedian and wants to marry her. But when she knows what she wants from her husband, will he fit the bill?",
      popularity: 4.779,
      poster_path: "/t7myQADi9CzpdcVWNWVAsK8o2WF.jpg",
      release_date: "2021-10-15",
      title: "Most Eligible Bachelor",
      video: false,
      vote_average: 2,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/j6r1jukdoJsOZ15RknTJ6wrACT1.jpg",
      genre_ids: [10749, 18],
      id: 826178,
      original_language: "hi",
      original_title: "भवई",
      overview:
        'The story is about the dream of Rajaram and its impact on the society. Rajaram an enthusiast by nature had only one dream of becoming an actor since his childhood. Being a village resident, he was deprived of that chance to live his dream. Will the duo be able to survive the obstacles or become a victim and succumb to the blind beliefs of the society? Who is the real Ravan, Rajaram or We "The Society"?',
      popularity: 6.722,
      poster_path: "/81ym0uDyWFxc3acigDe5e2Nk1gn.jpg",
      release_date: "2021-10-22",
      title: "Bhavai",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/D3i5IJlEpmoZdwnM828b5y9STz.jpg",
      genre_ids: [10749, 18],
      id: 887021,
      original_language: "te",
      original_title: "నాట్యం",
      overview:
        "In the ancient dance village Natyam, Sitara attempts to resurrect her Guru's forgotten masterpiece choreography and discovers the true power and purpose of Indian Classical Dance. To dance is to tell a story that can change our world.",
      popularity: 3.716,
      poster_path: "/eWXh5VQOMflOJI5uz5DJlJHr4Po.jpg",
      release_date: "2021-10-22",
      title: "Natyam",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/4nRkuqPjJR2yD9qT7ZuB48gX2m1.jpg",
      genre_ids: [18],
      id: 887862,
      original_language: "pa",
      original_title: "Yes I Am Student",
      overview:
        "The life and struggles of an International student, based on a true story.",
      popularity: 4.435,
      poster_path: "/xgSL81CetHhIXymPszYuYDD3EKp.jpg",
      release_date: "2021-10-22",
      title: "Yes I Am Student",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/5GTPOaWAH1LQIdNvEp41Btnx84p.jpg",
      genre_ids: [10749, 18],
      id: 663909,
      original_language: "te",
      original_title: "లవ్ స్టోరీ",
      overview:
        "Revanth and Mouni dream big when it comes to their lives. But with their social standing and gender proved to be a hindrance, will they manage to find a way to let their love prevail?",
      popularity: 4.132,
      poster_path: "/meFpLRe0ORU4nCQNc80tYynpPEI.jpg",
      release_date: "2021-09-24",
      title: "Love Story",
      video: false,
      vote_average: 8.1,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/4OWjaj13K6gRFMuE9SnjfQp00Eg.jpg",
      genre_ids: [10751, 10749, 18],
      id: 801505,
      original_language: "te",
      original_title: "వరుడు కావలెను",
      overview:
        "Bhoomi’s mother wants her to get married soon but she’s particular about what she wants. Akash returns to India after a successful stint abroad and while these opposite poles attract, will they make it work?",
      popularity: 4.669,
      poster_path: "/4J7zfkZBUDADKQdehSwFync1BR0.jpg",
      release_date: "2021-10-29",
      title: "Varudu Kaavalenu",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/vP9I3436K6AYvO1UR9R9YMsT6NY.jpg",
      genre_ids: [28, 35, 53],
      id: 673692,
      original_language: "ta",
      original_title: "டாக்டர்",
      overview:
        "An army doctor helps his love interest's family to find their kidnapped daughter.",
      popularity: 3.966,
      poster_path: "/ySPT0USsuDFG9pqHjI50GYOeQmj.jpg",
      release_date: "2021-10-09",
      title: "Doctor",
      video: false,
      vote_average: 7.5,
      vote_count: 3,
    },
  ],
  total_pages: 4,
  total_results: 65,
};
